def main():
    sex = input("Enter your sex (man/woman): ")
    print()
    age = int(input("Enter your age: "))
    print()
    weight = float(input("Enter your weight (kg): "))
    print()
    target_weight = float(input("Enter your target weight (kg): "))
    print()
    weeks = int(input("How fast do you want to achieve your goal (weeks)?: "))
    print()
    height = float(input("Enter your height (cm): "))
    print()
    
    print("How active are you during work?")
    print("1: Not active (sitting all day)")
    print("2: Slightly active (office work or similar)")
    print("3: Quite active (nurse or similar)")
    print("4: Active (gym instructor or similar)")
    print("5: Very active (craftsman or similar)")
    print()
    work_activity = int(input("Select your work activity level (1-5): "))
    print()

    print("How active are you during your spare time?")
    print("1: Not active (no exercise)")
    print("2: Slightly active (light exercise 2 times a week)")
    print("3: Quite active (moderate exercise 2 times a week)")
    print("4: Active (moderate exercise 3-4 times a week)")
    print("5: Very active (hard exercise at least 4 times a week)")
    print()
    spare_time_activity = int(input("Select your spare time activity level (1-5): "))
    print()
    
if __name__ == "__main__":
    main()